# Generated by Django 4.2.2 on 2023-08-03 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('tid', models.IntegerField(primary_key=True, serialize=False)),
                ('tname', models.CharField(max_length=20)),
                ('tsubject', models.CharField(max_length=15)),
            ],
        ),
    ]
